spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/yangzengsen/SpringCloud-Learning.git/
          search-paths: Dalston/config-repo
#          username:
#          password:

server:
  port: 1201